### ISSUE TITLE
SW-2: As a developer, I want to containerize this project

### ISSUE THREAD

**Issue by ivanljutyj** [TheCocoTeam/source-watcher-core#2]

**Comment by jpruiz114** [comment]
Closing this issue as Docker support was already added by @ivanljutyj in this commit: b0329d0642460c47d01ab5b171c1a8fdb3f3418b

**Comment by jpruiz114** [comment]
More changes to the Docker container might be required in the future since the original solution was for a web tool, and we currently have some web endpoints but as the project stands right now, it's the core of the tool which should be able to be used from the CLI, as a dependency from other projects or through a web browser.
